export type CableManufacturer = "Интеркабель" | "Южкабель" | "Типовые";

export type CableCategory =
  | "Огнестойкие (E30/E90)"
  | "Силовые медные (0.66/1 кВ)"
  | "Силовые алюминиевые"
  | "Бронированные"
  | "СПЭ 10 кВ"
  | "Пожарная сигнализация"
  | "Контрольные";

export interface CableSpec {
  id: string;
  name: string;
  manufacturer: CableManufacturer;
  category: CableCategory;
  diameterMm: number;
  voltage?: string;
  isPopular?: boolean;
}

export const CABLES_CATALOG: CableSpec[] = [
  /* =========================================================
     ИНТЕРКАБЕЛЬ (КИЕВ) - ОГНЕСТОЙКИЕ И БЕЗГАЛОГЕННЫЕ СИСТЕМЫ
     ========================================================= */
  // Огнестойкие (N)HXH FE180/E30 (30 минут под огнем)
  {
    id: "ik-hxh-e30-3x1.5",
    name: "(N)HXH FE180/E30 3×1.5",
    manufacturer: "Интеркабель",
    category: "Огнестойкие (E30/E90)",
    diameterMm: 11.5,
    voltage: "0.6/1 кВ",
    isPopular: true,
  },
  {
    id: "ik-hxh-e30-3x2.5",
    name: "(N)HXH FE180/E30 3×2.5",
    manufacturer: "Интеркабель",
    category: "Огнестойкие (E30/E90)",
    diameterMm: 12.5,
    voltage: "0.6/1 кВ",
    isPopular: true,
  },
  {
    id: "ik-hxh-e30-4x2.5",
    name: "(N)HXH FE180/E30 4×2.5",
    manufacturer: "Интеркабель",
    category: "Огнестойкие (E30/E90)",
    diameterMm: 13.5,
    voltage: "0.6/1 кВ",
    isPopular: false,
  },
  {
    id: "ik-hxh-e30-5x2.5",
    name: "(N)HXH FE180/E30 5×2.5",
    manufacturer: "Интеркабель",
    category: "Огнестойкие (E30/E90)",
    diameterMm: 14.5,
    voltage: "0.6/1 кВ",
    isPopular: false,
  },
  {
    id: "ik-hxh-e30-5x4",
    name: "(N)HXH FE180/E30 5×4",
    manufacturer: "Интеркабель",
    category: "Огнестойкие (E30/E90)",
    diameterMm: 16.5,
    voltage: "0.6/1 кВ",
    isPopular: true,
  },
  {
    id: "ik-hxh-e30-5x6",
    name: "(N)HXH FE180/E30 5×6",
    manufacturer: "Интеркабель",
    category: "Огнестойкие (E30/E90)",
    diameterMm: 18.0,
    voltage: "0.6/1 кВ",
    isPopular: false,
  },
  {
    id: "ik-hxh-e30-5x10",
    name: "(N)HXH FE180/E30 5×10",
    manufacturer: "Интеркабель",
    category: "Огнестойкие (E30/E90)",
    diameterMm: 21.0,
    voltage: "0.6/1 кВ",
    isPopular: true,
  },

  // Огнестойкие (N)HXH FE180/E90 (90 минут под огнем)
  {
    id: "ik-hxh-e90-3x1.5",
    name: "(N)HXH FE180/E90 3×1.5",
    manufacturer: "Интеркабель",
    category: "Огнестойкие (E30/E90)",
    diameterMm: 12.0,
    voltage: "0.6/1 кВ",
    isPopular: true,
  },
  {
    id: "ik-hxh-e90-3x2.5",
    name: "(N)HXH FE180/E90 3×2.5",
    manufacturer: "Интеркабель",
    category: "Огнестойкие (E30/E90)",
    diameterMm: 13.0,
    voltage: "0.6/1 кВ",
    isPopular: true,
  },
  {
    id: "ik-hxh-e90-4x4",
    name: "(N)HXH FE180/E90 4×4",
    manufacturer: "Интеркабель",
    category: "Огнестойкие (E30/E90)",
    diameterMm: 16.5,
    voltage: "0.6/1 кВ",
    isPopular: false,
  },
  {
    id: "ik-hxh-e90-5x4",
    name: "(N)HXH FE180/E90 5×4",
    manufacturer: "Интеркабель",
    category: "Огнестойкие (E30/E90)",
    diameterMm: 17.5,
    voltage: "0.6/1 кВ",
    isPopular: false,
  },
  {
    id: "ik-hxh-e90-5x6",
    name: "(N)HXH FE180/E90 5×6",
    manufacturer: "Интеркабель",
    category: "Огнестойкие (E30/E90)",
    diameterMm: 19.0,
    voltage: "0.6/1 кВ",
    isPopular: true,
  },
  {
    id: "ik-hxh-e90-5x10",
    name: "(N)HXH FE180/E90 5×10",
    manufacturer: "Интеркабель",
    category: "Огнестойкие (E30/E90)",
    diameterMm: 22.0,
    voltage: "0.6/1 кВ",
    isPopular: true,
  },
  {
    id: "ik-hxh-e90-5x16",
    name: "(N)HXH FE180/E90 5×16",
    manufacturer: "Интеркабель",
    category: "Огнестойкие (E30/E90)",
    diameterMm: 25.0,
    voltage: "0.6/1 кВ",
    isPopular: true,
  },
  {
    id: "ik-hxh-e90-4x25",
    name: "(N)HXH FE180/E90 4×25",
    manufacturer: "Интеркабель",
    category: "Огнестойкие (E30/E90)",
    diameterMm: 28.5,
    voltage: "0.6/1 кВ",
    isPopular: false,
  },
  {
    id: "ik-hxh-e90-4x50",
    name: "(N)HXH FE180/E90 4×50",
    manufacturer: "Интеркабель",
    category: "Огнестойкие (E30/E90)",
    diameterMm: 35.0,
    voltage: "0.6/1 кВ",
    isPopular: true,
  },
  {
    id: "ik-hxh-e90-4x95",
    name: "(N)HXH FE180/E90 4×95",
    manufacturer: "Интеркабель",
    category: "Огнестойкие (E30/E90)",
    diameterMm: 44.0,
    voltage: "0.6/1 кВ",
    isPopular: false,
  },
  {
    id: "ik-hxh-e90-4x120",
    name: "(N)HXH FE180/E90 4×120",
    manufacturer: "Интеркабель",
    category: "Огнестойкие (E30/E90)",
    diameterMm: 48.0,
    voltage: "0.6/1 кВ",
    isPopular: true,
  },

  // Огнестойкие экранированные (N)HXCH FE180/E90
  {
    id: "ik-hxch-e90-4x16-16",
    name: "(N)HXCH FE180/E90 4×16/16",
    manufacturer: "Интеркабель",
    category: "Огнестойкие (E30/E90)",
    diameterMm: 26.5,
    voltage: "0.6/1 кВ",
    isPopular: false,
  },

  // Огнестойкие для пожарной сигнализации JE-H(St)H
  {
    id: "ik-jeh-e30-1x2x0.8",
    name: "JE-H(St)H FE180/E30 1×2×0.8",
    manufacturer: "Интеркабель",
    category: "Пожарная сигнализация",
    diameterMm: 6.5,
    voltage: "300 В",
    isPopular: true,
  },
  {
    id: "ik-jeh-e30-2x2x0.8",
    name: "JE-H(St)H FE180/E30 2×2×0.8",
    manufacturer: "Интеркабель",
    category: "Пожарная сигнализация",
    diameterMm: 8.2,
    voltage: "300 В",
    isPopular: true,
  },
  {
    id: "ik-jeh-e90-2x2x0.8",
    name: "JE-H(St)H FE180/E90 2×2×0.8",
    manufacturer: "Интеркабель",
    category: "Пожарная сигнализация",
    diameterMm: 9.0,
    voltage: "300 В",
    isPopular: true,
  },
  {
    id: "ik-jeh-e90-4x2x0.8",
    name: "JE-H(St)H FE180/E90 4×2×0.8",
    manufacturer: "Интеркабель",
    category: "Пожарная сигнализация",
    diameterMm: 11.2,
    voltage: "300 В",
    isPopular: false,
  },

  // Силовые безгалогенные ВВГнгд (Интеркабель)
  {
    id: "ik-vvgngd-3x1.5",
    name: "ВВГнгд 3×1.5 (Интеркабель)",
    manufacturer: "Интеркабель",
    category: "Силовые медные (0.66/1 кВ)",
    diameterMm: 9.2,
    voltage: "0.66 кВ",
    isPopular: true,
  },
  {
    id: "ik-vvgngd-3x2.5",
    name: "ВВГнгд 3×2.5 (Интеркабель)",
    manufacturer: "Интеркабель",
    category: "Силовые медные (0.66/1 кВ)",
    diameterMm: 10.4,
    voltage: "0.66 кВ",
    isPopular: true,
  },
  {
    id: "ik-vvgngd-5x2.5",
    name: "ВВГнгд 5×2.5 (Интеркабель)",
    manufacturer: "Интеркабель",
    category: "Силовые медные (0.66/1 кВ)",
    diameterMm: 12.5,
    voltage: "0.66 кВ",
    isPopular: false,
  },
  {
    id: "ik-vvgngd-5x6",
    name: "ВВГнгд 5×6 (Интеркабель)",
    manufacturer: "Интеркабель",
    category: "Силовые медные (0.66/1 кВ)",
    diameterMm: 16.0,
    voltage: "0.66 кВ",
    isPopular: true,
  },
  {
    id: "ik-vvgngd-5x10",
    name: "ВВГнгд 5×10 (Интеркабель)",
    manufacturer: "Интеркабель",
    category: "Силовые медные (0.66/1 кВ)",
    diameterMm: 19.0,
    voltage: "0.66 кВ",
    isPopular: true,
  },

  /* =========================================================
     ЮЖКАБЕЛЬ (ХАРЬКОВ) - СИЛОВЫЕ, СПЭ, БРОНИРОВАННЫЕ, КОНТРОЛЬНЫЕ
     ========================================================= */
  // Силовые медные ВВГнг-LS / ВВГнгд (Южкабель)
  {
    id: "yk-vvgng-3x1.5",
    name: "ВВГнг-LS 3×1.5 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Силовые медные (0.66/1 кВ)",
    diameterMm: 9.5,
    voltage: "0.66 кВ",
    isPopular: true,
  },
  {
    id: "yk-vvgng-3x2.5",
    name: "ВВГнг-LS 3×2.5 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Силовые медные (0.66/1 кВ)",
    diameterMm: 10.8,
    voltage: "0.66 кВ",
    isPopular: true,
  },
  {
    id: "yk-vvgng-4x4",
    name: "ВВГнг-LS 4×4 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Силовые медные (0.66/1 кВ)",
    diameterMm: 14.0,
    voltage: "0.66 кВ",
    isPopular: false,
  },
  {
    id: "yk-vvgng-4x10",
    name: "ВВГнг-LS 4×10 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Силовые медные (0.66/1 кВ)",
    diameterMm: 18.0,
    voltage: "1 кВ",
    isPopular: true,
  },
  {
    id: "yk-vvgng-4x16",
    name: "ВВГнг-LS 4×16 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Силовые медные (0.66/1 кВ)",
    diameterMm: 21.0,
    voltage: "1 кВ",
    isPopular: true,
  },
  {
    id: "yk-vvgng-4x25",
    name: "ВВГнг-LS 4×25 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Силовые медные (0.66/1 кВ)",
    diameterMm: 24.5,
    voltage: "1 кВ",
    isPopular: false,
  },
  {
    id: "yk-vvgng-4x35",
    name: "ВВГнг-LS 4×35 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Силовые медные (0.66/1 кВ)",
    diameterMm: 27.5,
    voltage: "1 кВ",
    isPopular: true,
  },
  {
    id: "yk-vvgng-4x50",
    name: "ВВГнг-LS 4×50 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Силовые медные (0.66/1 кВ)",
    diameterMm: 32.0,
    voltage: "1 кВ",
    isPopular: true,
  },
  {
    id: "yk-vvgng-4x70",
    name: "ВВГнг-LS 4×70 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Силовые медные (0.66/1 кВ)",
    diameterMm: 36.5,
    voltage: "1 кВ",
    isPopular: false,
  },
  {
    id: "yk-vvgng-4x95",
    name: "ВВГнг-LS 4×95 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Силовые медные (0.66/1 кВ)",
    diameterMm: 41.5,
    voltage: "1 кВ",
    isPopular: true,
  },
  {
    id: "yk-vvgng-4x120",
    name: "ВВГнг-LS 4×120 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Силовые медные (0.66/1 кВ)",
    diameterMm: 45.0,
    voltage: "1 кВ",
    isPopular: true,
  },
  {
    id: "yk-vvgng-4x185",
    name: "ВВГнг-LS 4×185 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Силовые медные (0.66/1 кВ)",
    diameterMm: 54.5,
    voltage: "1 кВ",
    isPopular: false,
  },
  {
    id: "yk-vvgng-4x240",
    name: "ВВГнг-LS 4×240 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Силовые медные (0.66/1 кВ)",
    diameterMm: 61.5,
    voltage: "1 кВ",
    isPopular: true,
  },

  // Силовые алюминиевые АВВГнг-LS (Южкабель)
  {
    id: "yk-avvgng-4x16",
    name: "АВВГнг-LS 4×16 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Силовые алюминиевые",
    diameterMm: 19.5,
    voltage: "1 кВ",
    isPopular: false,
  },
  {
    id: "yk-avvgng-4x35",
    name: "АВВГнг-LS 4×35 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Силовые алюминиевые",
    diameterMm: 25.5,
    voltage: "1 кВ",
    isPopular: true,
  },
  {
    id: "yk-avvgng-4x70",
    name: "АВВГнг-LS 4×70 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Силовые алюминиевые",
    diameterMm: 33.5,
    voltage: "1 кВ",
    isPopular: true,
  },
  {
    id: "yk-avvgng-4x95",
    name: "АВВГнг-LS 4×95 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Силовые алюминиевые",
    diameterMm: 38.0,
    voltage: "1 кВ",
    isPopular: false,
  },
  {
    id: "yk-avvgng-4x120",
    name: "АВВГнг-LS 4×120 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Силовые алюминиевые",
    diameterMm: 41.5,
    voltage: "1 кВ",
    isPopular: true,
  },
  {
    id: "yk-avvgng-4x240",
    name: "АВВГнг-LS 4×240 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Силовые алюминиевые",
    diameterMm: 56.5,
    voltage: "1 кВ",
    isPopular: true,
  },

  // Бронированные кабели ВБбШвнг / АВБбШвнг (Южкабель)
  {
    id: "yk-vbbshv-4x16",
    name: "ВБбШвнг 4×16 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Бронированные",
    diameterMm: 22.5,
    voltage: "1 кВ",
    isPopular: true,
  },
  {
    id: "yk-vbbshv-4x35",
    name: "ВБбШвнг 4×35 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Бронированные",
    diameterMm: 29.5,
    voltage: "1 кВ",
    isPopular: false,
  },
  {
    id: "yk-vbbshv-4x70",
    name: "ВБбШвнг 4×70 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Бронированные",
    diameterMm: 37.5,
    voltage: "1 кВ",
    isPopular: true,
  },
  {
    id: "yk-vbbshv-4x120",
    name: "ВБбШвнг 4×120 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Бронированные",
    diameterMm: 46.5,
    voltage: "1 кВ",
    isPopular: true,
  },
  {
    id: "yk-avbbshv-4x150",
    name: "АВБбШвнг 4×150 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Бронированные",
    diameterMm: 48.0,
    voltage: "1 кВ",
    isPopular: false,
  },
  {
    id: "yk-avbbshv-4x240",
    name: "АВБбШвнг 4×240 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Бронированные",
    diameterMm: 59.0,
    voltage: "1 кВ",
    isPopular: true,
  },

  // Кабели с изоляцией из сшитого полиэтилена (СПЭ 10 кВ) (Южкабель)
  {
    id: "yk-spe-apvega-1x95-16",
    name: "АПвЭгаП-10 1×95/16 (Южкабель)",
    manufacturer: "Южкабель",
    category: "СПЭ 10 кВ",
    diameterMm: 29.5,
    voltage: "10 кВ",
    isPopular: true,
  },
  {
    id: "yk-spe-apvega-1x150-25",
    name: "АПвЭгаП-10 1×150/25 (Южкабель)",
    manufacturer: "Южкабель",
    category: "СПЭ 10 кВ",
    diameterMm: 33.0,
    voltage: "10 кВ",
    isPopular: true,
  },
  {
    id: "yk-spe-apvega-1x240-25",
    name: "АПвЭгаП-10 1×240/25 (Южкабель)",
    manufacturer: "Южкабель",
    category: "СПЭ 10 кВ",
    diameterMm: 37.5,
    voltage: "10 кВ",
    isPopular: true,
  },
  {
    id: "yk-spe-apvega-3x120-16",
    name: "АПвЭгаП-10 3×120/16 (Южкабель)",
    manufacturer: "Южкабель",
    category: "СПЭ 10 кВ",
    diameterMm: 61.5,
    voltage: "10 кВ",
    isPopular: true,
  },
  {
    id: "yk-spe-apvega-3x240-25",
    name: "АПвЭгаП-10 3×240/25 (Южкабель)",
    manufacturer: "Южкабель",
    category: "СПЭ 10 кВ",
    diameterMm: 74.5,
    voltage: "10 кВ",
    isPopular: false,
  },

  // Контрольные кабели КВВГнг-LS (Южкабель)
  {
    id: "yk-kvvg-4x1.5",
    name: "КВВГнг-LS 4×1.5 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Контрольные",
    diameterMm: 9.8,
    voltage: "0.66 кВ",
    isPopular: false,
  },
  {
    id: "yk-kvvg-7x1.5",
    name: "КВВГнг-LS 7×1.5 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Контрольные",
    diameterMm: 11.5,
    voltage: "0.66 кВ",
    isPopular: true,
  },
  {
    id: "yk-kvvg-10x1.5",
    name: "КВВГнг-LS 10×1.5 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Контрольные",
    diameterMm: 13.5,
    voltage: "0.66 кВ",
    isPopular: false,
  },
  {
    id: "yk-kvvg-14x1.5",
    name: "КВВГнг-LS 14×1.5 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Контрольные",
    diameterMm: 15.0,
    voltage: "0.66 кВ",
    isPopular: true,
  },
  {
    id: "yk-kvvg-19x1.5",
    name: "КВВГнг-LS 19×1.5 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Контрольные",
    diameterMm: 16.8,
    voltage: "0.66 кВ",
    isPopular: true,
  },
  {
    id: "yk-kvvg-27x1.5",
    name: "КВВГнг-LS 27×1.5 (Южкабель)",
    manufacturer: "Южкабель",
    category: "Контрольные",
    diameterMm: 20.0,
    voltage: "0.66 кВ",
    isPopular: false,
  },
];

export const POPULAR_CABLES = CABLES_CATALOG.filter((c) => c.isPopular);
